# makefile para corregir la actividad 2
# make <num_actividad> URL="<url al raw del fichero python>"
1:
	curl --silent ${URL} | python - 0 1 2
	curl --silent ${URL} | python - 1 1 2
	curl --silent ${URL} | python - 1 -5 6
2:
	curl --silent ${URL} | python - 2 4 7 8 3 5
3:
	curl --silent ${URL} | python - 7	
	curl --silent ${URL} | python - 2	
	curl --silent ${URL} | python - 9	
	curl --silent ${URL} | python - 10	
	curl --silent ${URL} | python - 12	
	curl --silent ${URL} | python - -1	
4:
	curl --silent ${URL} -o p4.py
	python p4.py 5
	rm p4.py
