# Generated by Django 2.2.3 on 2019-07-14 11:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 11, 25, 46, 741451, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
