# makefile para corregir la actividad 4
# make <num_actividad> URL="<url al raw del fichero python>"
1:
	curl --silent ${URL} | python - 78614630
2:
	curl --silent ${URL} | python -
3:
	curl --silent ${URL} | python - 2 "if i lose myself so i lose it all"
4:
	curl --silent ${URL} | python - 3.4 2.1 6.5 7.3 2.4 9.3 6.1
