# Generated by Django 2.2.3 on 2019-07-15 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190715_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', 'tittle'], 'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
        migrations.RenameField(
            model_name='page',
            old_name='title',
            new_name='tittle',
        ),
    ]
