# Generated by Django 2.2.3 on 2019-07-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190715_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', 'title'], 'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
        migrations.RenameField(
            model_name='page',
            old_name='tittle',
            new_name='title',
        ),
    ]
