# Generated by Django 3.1.3 on 2020-12-12 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='contentent',
            new_name='content',
        ),
    ]
