# makefile para corregir la actividad 3
# make <num_actividad> URL="<url al raw del fichero python>"
1:
	curl --silent ${URL} | python - -1
	curl --silent ${URL} | python - 12
	curl --silent ${URL} | python - 23
2:
	curl --silent ${URL} | python - -1
	curl --silent ${URL} | python - 5
3:
	curl --silent ${URL} | python - 24 18	
4:
	curl --silent ${URL} | python - -1
	curl --silent ${URL} | python - 7
