# makefile para corregir la actividad 6
# make <num_actividad> URL="<url al raw del fichero python>"
1:
	curl --silent ${URL} | python - "vamos a ver si ver si vamos vamos hola qué tal"
2:
	curl --silent ${URL} -o program2.py
	python program2.py
